### ISSUE TITLE
browserify bundle fails

### ISSUE THREAD

**Issue by sgimeno** [formly-js/angular-formly#186]
I'm trying to use angular-formly in a project bundled with browserify and the build is failing. The distributed `dist/formly.js` file seems to be not browserfiable:
```
$ browserify node_modules/angular-formly/dist/formly.js > bundle.js
Error: Cannot find module './formlyConfig.test' from '/Users/work/projects/foo/node_modules/angular-formly/dist'
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:42:25
    at load (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:60:43)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:66:22
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:21:47
    at FSReqWrap.oncomplete (fs.js:99:15)
```
The problem might come from `src/providers/formlyConfig.js` where a test file is required based on `ON_TEST` variable.

``` 
formlyConfig.tests = ON_TEST ? require('./formlyConfig.test')(ngModule) : null;
```
Any clues on how can we get formly to work with browserify?

**Comment by kentcdodds** [comment]
The line of code that browserify is looks at  (`dist/formly.js` which is the `main` in the `package.json`) actually looks like this:

```javascript
formlyConfig.tests = false ? require('./formlyConfig.test')(ngModule) : null;
```

This is because I'm using webpack's [DefinePlugin](http://webpack.github.io/docs/list-of-plugins.html#defineplugin) which will set that value to false when it compiles.

The error is coming from browserify trying to resolve that require statement, whereas the browser would never run that `require` statement, and when webpack builds, it's smart enough to know to not resolve it.

So the best solution (IMO) would be to figure out a way to configure browserify to not attempt to resolve that require statement.

**Comment by kentcdodds** [comment]
@sgimeno, could you try this solution to see if it will work for you: https://github.com/zertosh/unreachable-branch-transform

**Comment by kentcdodds** [comment]
Did that solution work for people? Does this still need to be open?

**Comment by kentcdodds** [comment]
Closing this issue as there hasn't been any activity on it for a while. Please reopen if this is an issue in the future.

**Comment by pmowrer** [comment]
Sorry to come back so quickly, but I ran into this immediately. To follow up where this was left off, `unreachable-branch-transform` would probably work. But, an even easier way is likely to include `angular-formly` in Browserify's `noParse` option since we can safely assume that `angular-formly` is a self-contained bundle. This way it won't be parsed for `require`s.

That worked. Unfortunately, Browserify still got stuck generating source maps with the following error:
```
Error: Invalid mapping: {"generated":{"line":9079,"column":7},"source":"webpack:///webpack/universalModuleDefinition","original":{},"name":null}
  at SourceMapGenerator_validateMapping [as _validateMapping] ([...]node_modules/browserify/node_modules/browser-pack/node_modules/combine-source-map/node_modules/inline-source-map/node_modules/source-map/lib/source-map/source-map-generator.js:275:15)
```
Haven't had time to dig into that yet, but disabling Browserify's source maps (`debug: false`) allows the bundling to complete successfully.

Trying to load `angular-formly` into our Angular app revealed the next problem. Since `angular-formly` wasn't parsed (`noParse`), it needs some help getting its dependencies: `angular` and `api-check`. We can do that using Browserify's `require` option. E.g. something like:

```
    browserify.require(require.resolve('api-check'), { expose: 'api-check' });
    browserify.require(require.resolve('angular'), { expose: 'angular' });
```

That was enough to get it working in our environment! We'd of course want to turn our source maps back on, but I would imagine it's not an insurmountable problem to solve.

**Comment by kentcdodds** [comment]
Wow @pmowrer, thanks for putting effort into getting this to work with browserify. I'm sorry that it's such a pain! Do you think you'd have a problem with simply using the minified file? That wont have the line that's causing the root issue here. I don't think you'd get sourcemaps for angular-formly, but hopefully that wont be a problem most of the time.

**Comment by kentcdodds** [comment]
Closing this as it should be fixed in 6.0.0

**Comment by pmowrer** [comment]
@kentcdodds So I'm back to have another look at formly + browserify. The 6.x upgrade to es6 modules solves the original problem! However, the [source map problem](https://github.com/formly-js/angular-formly/issues/186#issuecomment-91008338) is still happening when Browserify source maps are enabled (debug=true). Browserify internally uses https://github.com/thlorenz/combine-source-map to merge source maps from all bundled sources, which in turn uses https://github.com/mozilla/source-map, the eventual source of the error. I'm far from certain what the problem is or who's "responsible".

Decoding the inlined sourcemap, you get:
```json
{"version":3,"sources":["webpack:///webpack/universalModuleDefinition","webpack:///webpack/bootstrap 0853238e408d60f0f324","webpack:///./index.js",...
```
I'm not source map wiz, but the source URIs, `webpack:///...`, look like they're maybe specific to the webpack dev environment? 

Removing the inline source map from the mains, i.e. `angular-formly/dist/formly.js` and `api-check/dist/api-check.js` respectively, predictably solves the problem.

It makes me wonder, is bundling source maps with unminified source like `angular-formly` and `api-check` is doing typical? Looking through some other libraries (including `angular` itself), I can only see source maps being bundled with minified source (external). Is there a good reason why formly should inline source maps in unminified production builds?

**Comment by kentcdodds** [comment]
I actually had a conversation with @mzabriskie about this the other day. He informed me that including sourcemaps in your dist is actually a bad idea for this very reason I believe. I think that I'll have to find another way to accomplish the good development experience (perhaps a different distributable file?) For now, you could point to the minified version which doesn't include sourcemaps. Thanks!

**Comment by pmowrer** [comment]
Pointing to the minified version isn't super straightforward since Browserify works off of `main` in the `package.json`. It can be shimmed using browserify-shim to point to the minified file, which works, but `api-check.js` also needs to be shimmed. Since `api-check.js` is an internal dependency of `formly.js`, its not easily shimmed. 

I found it easier to write a Browserify transform to strip the source maps from `formly.js` and `api-check.js. Added bonus of not having to use the minified source. Here it is in case someone else finds it useful as a temporary workaround (lone dependency is [through2](https://github.com/rvagg/through2)):

```javascript
function(file) {
    var data = '';

    if (!/((angular-formly)|(api-check))\/dist\/((formly)|(api-check)).js$/.test(file)) {
      return through();
    }

    return through(write, end);

    function write(chunk, enc, callback) {
      data += chunk;
      callback();
    }

    function end(callback) {
      data = data.replace(/\/\/# sourceMappingURL.*/, '');
      this.push(data);
      callback();
    }
  }
```

**Comment by raibutera** [comment]
>  you could point to the minified version which doesn't include sourcemaps. Thanks!
Doesn't quite work, unfortunately, even when using `browserify-shim`. For some reason, browserify continues to complain about `angular` and `api-check` not being able to be found. 

I've used a couple of webpack-built frameworks (like https://github.com/js-data/js-data , which I know you're familiar with @kentcdodds) and they've not required anything more than the usual `browserify-shim` steps

**Comment by kentcdodds** [comment]
Yeah, I think that it's because I'm including sourcemaps. I'll try to pull those out in the next version (soon to be released)

**Comment by kentcdodds** [comment]
Might have fixed this. Everyone who's using browserify, please do:

`npm install api-check@7.2.3-beta.0`

`npm install angular-formly@6.4.2-beta.0`

Re-opening until someone tells me this fixes their problem. Please let me know asap :-)

**Comment by pmowrer** [comment]
@kentcdodds Verified on our end that it works! Nicely done :)

**Comment by kentcdodds** [comment]
Fixed and officially released in 6.4.2 :-) You're welcome :-)

**Comment by raibutera** [comment]
@kentcdodds literally I can't even.

For anyone who wants canonical browserify instructions that definitely work:

1. install `api-check` and `angular-formly` via __npm__ (NOT BOWER)
    - `npm install api-check 7.2.3 angular-formly 6.4.2 --save`
    - **NB:** No browserify shim or dependency listing in your `package.json`'s `browserify` configuration object is necessary.
2. in your javascript, require `api-check` and `angular-formly`
3. in your angular module declaration, insert `'formly'` into the dependency array

**example**:
```javascript
var angular = require('angular');
require('api-check');
require('angular-formly');

var app = angular.module('anAppThatCanFinallyUseFormly', ['formly']);
````

**Comment by kentcdodds** [comment]
Could you verify that this works as well (it should):

```javascript
var angular = require('angular');
require('api-check');

var app = angular.module('anAppThatCanFinallyUseFormly', [require('angular-formly')]);
```

**Comment by kentcdodds** [comment]
**Note the edit:** You shouldn't have to even require `api-check` because `angular-formly` will require it itself.

**Comment by kentcdodds** [comment]
Here's the final steps (I'll put into the docs if someone tells me this works):

1. install api-check and angular-formly via npm (NOT BOWER)
   - npm install api-check 7.2.3 angular-formly 6.4.2 --save
   - NB: No browserify shim or dependency listing in your package.json's browserify configuration object is necessary.
2. in your javascript, require angular-formly in your module's dependencies array

```javascript
var angular = require('angular');
var app = angular.module('anAppThatCanFinallyUseFormly', [require('angular-formly')]);
```
